### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by markusfi** [StefanKert/vsts-codesigning-task#3]
Hi there,
I get an invalid password error not matter how I specify my password. I tried parameter, variable (plain text), variable (encrypted), I even changed the password, but no lock.
What can be wrong?

`cmd: 'D:\\a\\_tasks\\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\\1.0.1\\signtool.exe sign /fd SHA256 /t http://timestamp.digicert.com /f D:\\a\\_temp\\HanakoPG.pfx /p *** D:\\a\\1\\s\\HanakoOnline\\HanakoPG\\Releases\\setup.exe

2018-06-11T18:25:10.1899131Z ##[error]Command failed: D:\a\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.0.1\signtool.exe sign /fd SHA256 /t http://timestamp.digicert.com /f D:\a\_temp\HanakoPG.pfx /p *** D:\a\1\s\HanakoOnline\HanakoPG\Releases\setup.exe

SignTool Error: The specified PFX password is not correct.
`

**Comment by StefanKert** [comment]
I guess you are using a .pfx that has been added to the secure files in vsts. Can you try to download this file and use the password you provided? Probably you uploaded a wrong password. 

If the password is right, can you please try to run the script manually and double check if it is working or not? You should be able to access the signtool through your developer console. 

```
signtool.exe sign /fd SHA256 /t http://timestamp.digicert.com /f PATHTOPFX /p PASSWORD FILETOSIGN
```

If this works offline we probably have some encoding issues. If you need any further help on this feel free to ask :)

**Comment by markusfi** [comment]
I am using a .pfx as a secure file. I do not know how to download a secure file (isn't the purpose of a secure file that you cannot download it?) I already tried with another file, changed password, password as plain text etc.  It works on my local machine using the same password, but it does not on vsts. How can I access a developer console on vsts?

**Comment by StefanKert** [comment]
Yes definetly it is the main purpose. 

So it I understand right, it is not working with the other certificate as well, but offline you can open it with your password.

By developer console I was referring to the visual studio developer console/prompt. Can you try to run the signtool manually with one of those pfx files and tell me if it works there?

**Comment by markusfi** [comment]
Found it: I changed the password to only digits and I changed the certificate encryption cipher to 3DES & SHA1: I Works now. 

I checked my disk (Win10, Ver10.0.17134.81) for different Versions of SignTool.exe and there are many...some of them are signed on 20. 4. 2018, 6. 1. 2017, 28. 7. 2016 (same as your version in github), 19. 3. 2010 (one of the oldest on my system).
Could you please update to the current Version of SignTool.exe in your addon so that it works with all certificate encryption ciphers (AES/SHA256) - older encryption ciphers are probably insecure.
To reproduce: You need the current WIndows 10 release to export the certificate using this .pfx private key encryption.

Besides: Thanks you very much for this brilliant tool!

**Comment by StefanKert** [comment]
First of all sorry for the delay. Second: Thanks for the info! Glad that this is working out now and also thanks for the heads up regards the update. I will update that stuff asap!

:) Glad that my tool is helping you  :) Feedback and feature requests are greatly appreciated :)!
