### ISSUE TITLE
The specified PFX password is not correct?

### ISSUE THREAD

**Issue by jholovacs** [StefanKert/vsts-codesigning-task#7]
Password is confirmed to be correct, hashing mechanism should be SHA256, we can import the certificate locally without issue, but we get this error:

> 2019-02-25T13:50:15.9108131Z SignTool Error: The specified PFX password is not correct.
> 2019-02-25T13:50:15.9108601Z 
> 2019-02-25T13:50:15.9108813Z     at ChildProcess.exithandler (child_process.js:204:12)
> 2019-02-25T13:50:15.9108976Z     at emitTwo (events.js:106:13)
> 2019-02-25T13:50:15.9109154Z     at ChildProcess.emit (events.js:191:7)
> 2019-02-25T13:50:15.9109310Z     at maybeClose (internal/child_process.js:886:16)
> 2019-02-25T13:50:15.9109497Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 2019-02-25T13:50:15.9109670Z   killed: false,
> 2019-02-25T13:50:15.9110367Z   code: 1,
> 2019-02-25T13:50:15.9110679Z   signal: null,
> 2019-02-25T13:50:15.9168732Z ##[error]Command failed: D:\a\_tasks\codesigning_0e0f3bf7-d96c-45d6-aa76-f9afb71fb77e\1.1.0\signtool.exe sign /fd SHA256 /t http://timestamp.digicert.com /f D:\a\_temp\ErpMaestroCSCert.pfx /p [Our Password] D:\a\r1\a\_artifact\Application\coreapp\win7-x64\ErpMaestro.Agents.Application.exe
> SignTool Error: The specified PFX password is not correct.
>

**Comment by jholovacs** [comment]
It turns out that the PFX was exported from Windows as AES256/SHA256, and signtool.exe couldn't read it.  When we exported as 3DES/SHA1 it worked fine.

**Comment by seabass223** [comment]
you saved me a lot of headache. been struggling with this for 3 days. what a pain. thank you so much.
